{% set name = "xradarsat2" %}
{% set version = "2024.11.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xradarsat2-{{ version }}.tar.gz
  sha256: eac40faf88afed74eddc7512a51401c87d2515937f0ed94c1891a21fc90a4260

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64.0
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.9
    - xmltodict
    - numpy
    - xarray
    - rasterio
    - rioxarray
    - dask-core
    - affine
    - regex
    - pyyaml

test:
  imports:
    - xradarsat2
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/umr-lops/xradarsat2/
  summary: xarray reader for Level-1 SAR radarSat2 products
  license: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/umr-lops/xradarsat2/
  doc_url: https://cerweb.ifremer.fr/datarmor/doc_lib_reader_RS2/html/
extra:
  recipe-maintainers:
    - yreynaud
    - agrouaze
